name: demo
on:
  push:
    branches:
      - 'main'

jobs:
  conditional_step:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3
      with:
        repository: hello-world-with-gradle
    - run: cd /home/runner/work/test-actions/test-actions
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew build
    - name: Show path
      run: ls
    - name: Execute jar
      run: java -jar Lavalink.jar
      
